---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/2/25 14:29
---

function validPlayer(player)

    if player == nil then
        return false
    end

    if not player.valid then
        return false
    end

    return true

end