---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/2/25 14:29
---

function validPlayer(player)

    if player == nil then
        return false
    end

    if not player.valid then
        return false
    end

    return true
end

--从事件中获取玩家实例
function getPlayer(event)

    local pl = game.players[event.player_index]

    if pl == nil then
        return nil
    end

    if pl.valid == false then
        return nil
    end

    return pl
end