---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/2/25 21:43
---


function getCash(player)

    local cashQuantity = player.get_main_inventory().get_item_count("coin")

    if cashQuantity == nil then
        return 0
    end

    return cashQuantity

end


function removeCash(player,quantity)

    --扣费失败
    if getCash(player) < quantity then
        return false
    end

    --扣费成功
    player.get_main_inventory().remove({name="coin", count=quantity})
    return true

end