---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/2/23 17:51
---

extConf = {}


extConf.placeTextWithPlayerJoining="KspTooi"

extConf.placeTextWithPlayerSpawn = {
    text1= "欢迎加入KspTooi服务器",
    text2= "欢迎",
    text3= "回家"
}

--显示版本
extConf.displayVersion="开发版本:1.35-E"

--是否允许玩家加入主团队
extConf.enableMainTeam=false

--Discord
extConf.serverInfoDiscordText = "discord.gg/trnpcen"
--QQGroup
extConf.serverInfoQQGroupText = "QQ群:860179317"






return extConf