---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/2/23 17:51
---

extConf = {}


extConf.placeTextWithPlayerJoining="KspTooi"

extConf.placeTextWithPlayerSpawn = {
    text1= "欢迎加入KspTooi服务器",
    text2= "欢迎",
    text3= "回家"
}


extConf.jail = {
    text1= "有点小失望☹",
}


return extConf
