---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/3/2 23:06
---

guiEnum = {}

--refresh菜单的元素枚举
guiEnum.refresh = {
    initBtn = "refresh_button"
}



--ext菜单的元素枚举
guiEnum.extMenuEnum = {
    extMenuBtn = "extMenuBtn"
    ,extMenu = "extMenu"
}

--ServerNews菜单的元素枚举


return guiEnum