---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/2/26 13:53
---

--校验 实体 原因与阵营
function validForEntityAndCause(event)

    local entity = event.entity

    local cause = event.cause

    --实体校验
    if entity == nil and not entity.valid then
        return false
    end

    if cause == nil then
        return false
    end

    if not entity.force.index == game.forces.enemy.index then
        return false
    end

    return true

end

