---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/2/26 20:50
---

---抗性计算机

---根据百分比校正
function correctionForPercentage(originValue,percentage)

    --抗性调整
    return originValue * (percentage/100)

end


