---ite
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/3/2 20:29
---
local modGui = require("mod-gui")
require("lib.ksptooi.commons.ExportModule")


--创建ext菜单按钮
function initExtMenuBtn(player)

    local btnFlow = modGui.get_button_flow(player)

    if btnFlow.extMenuBtnId ~= nil then
        return
    end

    btnFlow.add({
        name = guiEnum.extMenu.btnInit
        ,type = "sprite-button"
        ,caption = "我的菜单(EXT)"
        ,style=modGui.button_style
    })

end

--ext菜单按钮被点击
function clickExtMenuBtn(event)


    

    local player = getPlayer(event)



end




--渲染ext菜单
function displayExtMenu(event)




end