---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/2/25 11:12
---

require("lib.ksptooi.commons.PlayerLib")
require("lib.ksptooi.commons.PlayerCashLib")
require("lib.ksptooi.teleport.TpRequestStorage")



---发送传送请求
function teleportToPlayer(command)

    if(command.parameter == nil)then
        game.print("缺少参数")
        return
    end

    local player = game.players[command.player_index]

    local target = game.players[command.parameter]


    if not validPlayer(target) then
        player.print("玩家不存在")
        return
    end

    if insertTpRequest(player,target)then

        player.print("传送请求已经发送至:"..target.name.." 等待对方接受")
        target.print(player.name.."请求传送至你的位置. 输入/tpaccept 接受这个请求")

        return
    end

    player.print("你已经发送过传送请求了")

    --player.teleport({target.position.x,target.position.y},GAME_SURFACE_NAME)
end


---接受请求
function teleportAccept(command)

    local target = game.players[command.player_index]

    local tpReq = getTpRequest(target)


    if tpReq == nil then
        target.print("当前没有待处理传送请求")
        return
    end

    if not validPlayer(tpReq.from)then
        target.print("接受请求失败,玩家不可用.")
        return
    end


    local from = game.players[tpReq.from.name]

    ---不可传送
    if (from.position.x < 20 and from.position.x > -20) or (from.position.y < 20 and from.position.x > -20) then
        target.print("接受请求成功,但对方的位置不允许进行传送.")
        removeTpRequest(target)
        return
    end

--[[    if (player.vehicle) then
        player.print("先生，请先下车，然后再尝试购买...")
        return
    end]]

    ---扣费
    if not (removeCash(from,200))then
        target.print("接受请求成功,但对方没有足够的现金进行此次传送.")
        removeTpRequest(target)
        return
    end


    target.print("接受请求成功.")
    from.print("对方已接受你的传送请求.")
    tpReq.from.teleport({target.position.x,target.position.y})
    removeTpRequest(target)

end


commands.add_command("tpa","tpa",teleportToPlayer)

commands.add_command("tpaccept","tpa",teleportAccept)

commands.add_command("tpdeny","tpa",teleportToPlayer)