---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/2/25 16:50
---

---TP请求存储在此
---from target
local tpRequest = {

}


function insertTpRequest(from,target)

    --一个玩家只能拥有一个传送请求
    for i,v in pairs(tpRequest) do

        if v.from.name == from.name then

            if(v.target == target) then
                return false
            end

            table.remove(tpRequest,i)
        end

    end

    table.insert(tpRequest,{from=from,target=target})
    return true
end

--获取请求
function getTpRequest(targetPlayer)

    for i,v in pairs(tpRequest) do

        if v.target.name == targetPlayer.name then
            return v
        end

    end

    return nil
end

--移除请求
function removeTpRequest(targetPlayer)

    for i,v in pairs(tpRequest) do

        if v.target.name == targetPlayer.name then
            table.remove(tpRequest,i)
        end

    end

end
