---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/2/24 0:17
---

require("lib.ksptooi.WorldCleaer")



--[[
commands.add_command("worldClear", "清理无用的地图区块",removeTiles(command));]]


commands.add_command("worldClear", "清理无用的地图区块", function(command)
    removeTiles(command)
end)
