---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/2/26 0:42
---

require 'utils.data_stages'
_LIFECYCLE = _STAGE.control
local event = require 'utils.event'

---对虫巢的抗性调整


local onEntityDamage = function(event)

    --死亡实体
    local entity = event.entity

    --原因
    local cause = event.cause

    --实体校验
    if not (entity and entity.valid) then
        return
    end

    --原因校验
    if not cause then return end

    --如果阵营不为enemy则return
    if not entity.force.index == game.forces.enemy.index then
        return
    end


    if entity.health < 30 then
        return
    end


    --对激光的抗性
    if event.damage_type.name == "laser" then

        --降低95%伤害
        entity.health = entity.health + (event.final_damage_amount * (1-0.05))

        return
    end



    game.print("血量"..entity.health)
    game.print("最终血量"..event.final_health)

--[[    entity.health = entity.health + 0.5
    log("HEATH:"..entity.health)]]

--[[    --如果不是虫巢
    if entity.type ~= "unit-spawner" then
        return
    end]]






    --对蜘蛛的抗性
--[[    if cause.valid then

        if event.cause.name == "spidertron" then
            entity.health = entity.health - damage *0.1
            game.print("伤害抗性增加 - 蜘蛛")
            return
        end

    end]]




end




event.add(defines.events.on_entity_damaged,onEntityDamage)