---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2021/2/24 0:15
---



function removeTiles(command)


    local surface = game.players[command.player_index].surface

    for chunk in surface.get_chunks() do

        local a = surface.count_tiles_filtered{area=chunk.area,name="out-of-map"}

        local b = surface.count_entities_filtered{area=chunk.area,force=game.forces.player}

        game.print("FilteredChunk:"..a.."\nEntitiesFiltered:"..b)


        if a > 0 or b == 0 then


            game.surfaces["oarc"].delete_chunk({chunk.x,chunk.y})
            --surface.delete_chunk({chunk.x,chunk.y})

        end

    end


end
